### ISSUE TITLE
Oakley

### ISSUE THREAD

**Issue by SaymanNsk** [MrKWatkins/Ast#11]
Yo! Hello!
Don`t know how to write to you....
Any news about Oakley?
When?
Where?))

**Comment by MrKWatkins** [comment]
Hi!

So the project is still on going. I didn't have anytime to dedicate to it for a few years due to my private life getting in the way. I then decided to rewrite pretty much from scratch at the end of last year, this time compiling straight to Z80 rather than to C, as, well, that's more fun. :) That is taking quite a while, plus I've taken several diversions. Firstly I decided to spin of some of the shared code into this AST shared library.

I then started another library to allow me to assemble Z80 code from C#. I was enjoying coding that so decided to turn it into a fully fledged assembler too... I then went back to Oakley, realised I needed some way to unit test Z80 code in C# so expanded the assembler to include a Z80 emulator... And then added a disassembler and formatter for good measure...

So current plan is to get the AST project fully documented at version 1.0 by the end of the year. Then I will tidy up, document and finish off the assembler/disassembler/emulator project called OakAsm and release that. (It's currently private until the code is a bit tidier) Hopefully Q1 next year? Then back onto Oakley as my main focus. Hoping to have something that can compile basic code to Z80 by the middle of 2024 (I'm close to compiling very basic programs, just need a good week with no distractions) and something more fully featured by the end of 2024.

Thanks for your interest in the project!

Kev
